language: java
jdk:
  - openjdk11
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
script: mvn clean verify -Dmaven.javadoc.skip=true
dist: xenial
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-3.8.1"
before_install:
- export M2_HOME=$HOME/apache-maven-3.8.1
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH
